### ISSUE TITLE
Remove the possibility to square an image, so the aspect ratio only is 4/5

### ISSUE THREAD

**Issue by dadyownes15** [LeGoffMael/insta_assets_picker#10]
How do i remove the button on on image picker screen, that allows users to change their aspect ratio of their images to 1/1? 
<img width="205" alt="Screen Shot 2023-05-09 at 9 46 20 AM" src="https://user-images.githubusercontent.com/116811853/237029566-ca69ca50-cfa4-4871-aefb-448784323e28.png">

**Comment by LeGoffMael** [comment]
You can set the list of available aspect ratios since the latest `1.5.0`.

```dart
InstaAssetPicker.pickAssets(
  context,
  title: 'Select images',
  cropDelegate: InstaAssetCropDelegate(cropRatios: [1]), // can add any ratio you want
  onCompleted: (cropStream) {},
),
```
