### ISSUE TITLE
image not  load  

### ISSUE THREAD

**Issue by kdChavada** [LeGoffMael/insta_assets_picker#12]
![image](https://github.com/LeGoffMael/insta_assets_picker/assets/72186768/9e651e15-7acc-49a8-9175-2cdda63109b4)
this  issue  Facing specific Device

**Comment by LeGoffMael** [comment]
Please provide more information, i cannot help you without details.
1. you said it is device specific, what device are you using?
2. with which image extensions do you encounter this problem?
3. is there a pattern to reproduce this issue?
4. do you have any file / or a way to reproduce this error?

also you should check if you have a similar issue with [wechat_assets_picker](https://pub.dev/packages/wechat_assets_picker) package, if so, it comes from there.
