### ISSUE TITLE
Request for Assistance: Implementing Pinch-Zoom(Crop) Feature on Images

### ISSUE THREAD

**Issue by Rohan-ManekTech** [LeGoffMael/insta_assets_picker#17]
Dear @LeGoffMael ,

I hope this message finds you well. My name is Rohan, and I am an enthusiastic developer and a user of your fantastic insta_assets_picker on GitHub. I've been exploring your repository and found it to be an excellent resource for pinch to crop an image.

I am currently working on a project that requires the implementation of a pinch-zoom(crop) feature for images, and I believe your expertise in this area could be immensely valuable. I have seen the exemplary code and solutions you've provided in the past, and I was wondering if you could spare a moment to guide me on how to achieve this functionality in my project.

My intention is to allow users to interactively pinch and zoom (crop)into images, offering a seamless and intuitive user experience. Since you have demonstrated proficiency in similar areas within your repository, I am hopeful that you could share some insights, code snippets, or pointers to libraries that could help me accomplish this task.

Warm regards,
Rohan Darji

**Comment by LeGoffMael** [comment]
You should look into [image_crop](https://pub.dev/packages/image_crop) package. This is was this library is using.
