### ISSUE TITLE
New version of we chat assets picker 8.6.0 is not working. 

### ISSUE THREAD

**Issue by ps6067966** [LeGoffMael/insta_assets_picker#19]
![image](https://github.com/LeGoffMael/insta_assets_picker/assets/26248740/5dc76af8-fcc9-4248-83cc-2b6840ac2ec1)

**Comment by AlexV525** [comment]
Fixed by #18.

**Comment by LeGoffMael** [comment]
Fix available in new 1.5.2 version.
