### ISSUE TITLE
[Feature] Images is loading very slow

### ISSUE THREAD

**Issue by princeflutterdev** [LeGoffMael/insta_assets_picker#20]
In my iphone i have approx 20k image stored . when i use this in my flutter application it take approx 5-10 min to load the images.
so my concern is only , this is not bug this is just feature can we implement kind of pagination or limit to load images .

**Comment by LeGoffMael** [comment]
That's weird cause i also have 20k items in my gallery on my iphone, and it is loading in a couple of seconds.
Could you provide more details on how you're using it ? Did you try to run the example ?

**Comment by princeflutterdev** [comment]
> That's weird cause i also have 20k items in my gallery on my iphone, and it is loading in a couple of seconds. Could you provide more details on how you're using it ? Did you try to run the example ?

yes exactly some of my device didn't take much time but the issue is only in iphone 14

also can we have camera capture fuctionlity in this like instagram have

**Comment by LeGoffMael** [comment]
Without more information i am not sure how can I help you. Maybe you should check for more information in the [flutter_wechat_assets_picker](https://github.com/fluttercandies/flutter_wechat_assets_picker) package.

For the camera feature, i am not planning to add more functionality soon. However, you could use the special item argument to make a button that open the camera. For example :

```dart
InstaAssetPicker.pickAssets(
      context,
      title: 'Select images',
      specialItemBuilder: (context, asset, id) {
        // return a button that open the camera
      },
      // since the list is revert, use prepend to be at the top
      specialItemPosition: SpecialItemPosition.prepend,
      ...
    ),
```
