### ISSUE TITLE
[Feature] - SingleMode

### ISSUE THREAD

**Issue by ibhanu** [LeGoffMael/insta_assets_picker#26]
when maxAsset is set to 1, When user select new image, prevSelect should get replaced and possiblly remove the showing of count as well for GridView for when single Mode isEnabled

In weChat they use isSingleModel which then uses maxAssets

**Comment by LeGoffMael** [comment]
Hi,
Thank you for pointing that out!
Please check out the new 2.1.0 version which i believe enable the single mode properly
