### ISSUE TITLE
when adding the new version then throwing the bellow issue.

### ISSUE THREAD

**Issue by rajivmegamind** [LeGoffMael/insta_assets_picker#29]
Resolving dependencies...
Because insta_assets_picker >=1.6.0 depends on extended_image ^8.1.0 which depends on extended_image_library ^3.6.0, insta_assets_picker >=1.6.0 requires extended_image_library ^3.6.0.
And because extended_image_library >=3.5.3 <4.0.0-dev depends on http_client_helper ^3.0.0 which depends on http ^1.0.0, insta_assets_picker >=1.6.0 requires http ^1.0.0.
So, because secondfit depends on both http ^0.13.5 and insta_assets_picker ^2.1.0, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on insta_assets_picker: flutter pub add insta_assets_picker:^1.5.2

**Comment by rajivmegamind** [comment]
1. ****when change the package version insta_assets_picker:^1.5.2 this thwn issue is gone but throwing the bellow error****


Running Gradle task 'assembleDebug'...
../../../.pub-cache/hosted/pub.dev/extended_image-8.0.2/lib/src/image/painting.dart:202:13: Error: 'ImageTilingInfo' isn't a type.
      final ImageTilingInfo info =
            ^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/extended_image-8.0.2/lib/src/image/painting.dart:203:11: Error: Method not found: 'createTilingInfo'.
          createTilingInfo(repeat, rect, destinationRect, sourceRect);
          ^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* Where:
Script '/Users/mac/Downloads/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1297

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/mac/Downloads/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by LeGoffMael** [comment]
> So, because secondfit depends on both http ^0.13.5 and insta_assets_picker ^2.1.0, version solving failed.

The error is describing the issue, you should upgrade the version of the `http` package to at least `^1.0.0` in your pubspec
