### ISSUE TITLE
i got that error

### ISSUE THREAD

**Issue by axroromonov** [LeGoffMael/insta_assets_picker#30]
Could not build the precompiled application for the device.
Error (Xcode): ../../.pub-cache/hosted/pub.dev/photo_manager-2.7.2/lib/src/internal/image_provider.dart:72:28: Error: The parameter 'decode' of the method 'AssetEntityImageProvider.load' has type 'Future<Codec> Function(ImmutableBuffer, {TargetImageSize Function(int, int)? getTargetSize})', which does not match the corresponding type, 'Future<Codec> Function(Uint8List, {bool allowUpscaling, int? cacheHeight, int? cacheWidth})', in the overridden method, 'ImageProvider.load'.

Error launching application on iPhone 14 Pro.

**Comment by LeGoffMael** [comment]
Please try the new 2.2.0 version
