### ISSUE TITLE
Not working in Chrome

### ISSUE THREAD

**Issue by abdibrokhim** [LeGoffMael/insta_assets_picker#34]
I have run the app, and tried with Chrome. But Camera Picker did not work. Help me

<img width="1197" alt="Screenshot 2023-11-24 at 18 33 30" src="https://github.com/LeGoffMael/insta_assets_picker/assets/92748035/587040a7-a5d0-49cd-be0e-538d63f18c78">

**Comment by LeGoffMael** [comment]
This package does not support web

**Comment by abdibrokhim** [comment]
> This package does not support web

ahh, really, i got it thank you
