### ISSUE TITLE
Is there a way to skip the "Unable to access all assets on the device"

### ISSUE THREAD

**Issue by Egemen-Arslandogan** [LeGoffMael/insta_assets_picker#35]
onPermissionDenied method not working. I would like to remove the "Unable to access all assets on the device" screen and allow them to continue to the "Continue with limited access" screen automatically if they chose to only give limited access. How can i do that?

**Comment by Theoarnan** [comment]
> onPermissionDenied method not working. I would like to remove the "Unable to access all assets on the device" screen and allow them to continue to the "Continue with limited access" screen automatically if they chose to only give limited access. How can i do that?

![image](https://github.com/LeGoffMael/insta_assets_picker/assets/48319849/b8bd7dc0-f089-49b8-b834-db6a1a2bf402)
I have same problem with you bro.. 

Please help help 😭

**Comment by Egemen-Arslandogan** [comment]
> > onPermissionDenied method not working. I would like to remove the "Unable to access all assets on the device" screen and allow them to continue to the "Continue with limited access" screen automatically if they chose to only give limited access. How can i do that?
> 
> ![image](https://private-user-images.githubusercontent.com/48319849/288276061-b8bd7dc0-f089-49b8-b834-db6a1a2bf402.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4ODM5NDEsIm5iZiI6MTcwMTg4MzY0MSwicGF0aCI6Ii80ODMxOTg0OS8yODgyNzYwNjEtYjhiZDdkYzAtZjA4OS00OWI4LWI4MzQtZGI2YTFhMmJmNDAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDE3MjcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzZWI0ZjA3YjliNmJlMTA5MTliYjc2OWIxN2M5NmY5N2IxZmQwMjhlNTVlNGM1YTgyMzQwYjFkMDU5MDZjYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HSQg07qtsxtnF_zqp84m6QwCH5By7977cOumVcj1PSg) I have same problem with you bro..
> 
> Please help help 😭

My solution;

*Download the library manually from github and add it to the project main directory.
* Give path extension from your pubspec.yaml file:
  ```
 insta_assets_picker:
     path: 'insta-assets-picker'

```
*Open the lib/src/assets_picker.dart file from the library files you added to your project and remove the following method

`ps = await _permissionCheck(); (x2)
`

**Comment by LeGoffMael** [comment]
Related to https://github.com/fluttercandies/flutter_wechat_assets_picker/issues/285. I will expose the `limitedPermissionOverlayPredicate` parameter so that you can use it.

```dart
InstaAssetPicker.pickAssets(
  context,
  ...
  limitedPermissionOverlayPredicate: (PermissionState state) => false, // here return whether to show the limited access screen or not based on the permission state
);
```

**Comment by LeGoffMael** [comment]
New versions `2.2.1` & `2.3.0-dev.2` were deployed with the change. Please check it out :)

**Comment by Egemen-Arslandogan** [comment]
Thanks

> fluttercandies/flutter_wechat_assets_picker#285


This is the feature I was looking for! Thanks a lot :)
