### ISSUE TITLE
Fix linter warnings with Flutter 3.7

### ISSUE THREAD

**Issue by AlexV525** [LeGoffMael/insta_assets_picker#4]
https://github.com/LeGoffMael/insta_assets_picker/blob/1edcf7a0218919d4595d30be4f8091dd50781e8f/lib/src/widget/insta_asset_picker_delegate.dart#L561

Multiple fields in the `ThemeData` has been deprecated since Flutter 3.7.

**Comment by LeGoffMael** [comment]
Thank you for the heads-up, i will check it to make it compatible with Flutter 3.7 in the next release

**Comment by LeGoffMael** [comment]
Fixed in 1.1.1
