### ISSUE TITLE
Request for video support

### ISSUE THREAD

**Issue by joachimbulow** [LeGoffMael/insta_assets_picker#42]
Are there any plans on releasing support for video?

Would be insanely helpful, also since the wechat_assets_picker library supports it

**Comment by joachimbulow** [comment]
@LeGoffMael 
I would be willing to work on this.
Would you be willing to  guide me in the right direction?

**Comment by rezam92** [comment]
I added this feature in [https://github.com/LeGoffMael/insta_assets_picker/pull/44](url)

**Comment by LeGoffMael** [comment]
I discussed about this feature in another [issue](https://github.com/LeGoffMael/insta_assets_picker/issues/9#issuecomment-1547081731) :

> Video crop support would be indeed a really nice feature to this package, but requires a lot of work and time that i unfortunately won't have soon. My plan is to adapt my other package [video_editor](https://github.com/LeGoffMael/video_editor), to use a similar UI than the one used in this package. I also have to think about the exportation process, if on the device or not. If you're motivated and want to help build this feature, you could check how to adapt the video_editor crop UI ([LeGoffMael/video_editor#114](https://github.com/LeGoffMael/video_editor/issues/114)), if you could open a PR with this feature i would love to review it.
> 
> If you just want to display videos & images, you can look into the [example i made in flutter_wechat_assets_picker](https://github.com/LeGoffMael/video_editor). There is no crop action, but you can select either images, videos or both. Although it seems that there is some issue with the video player ([fluttercandies/flutter_wechat_assets_picker#416](https://github.com/fluttercandies/flutter_wechat_assets_picker/issues/416)), it might help you to achieve your goal.

The goal of this package is to be able to pick (one or more) assets of the same crop ratio value.

To support video assets, my current idea is to :
- update the picker to allow video assets (similar to @rezam92 work in #44)
- update the current crop view to support a video thumbnail or a video player
- save the crop values for each videos and return them in `onCompleted`
- create a new widget to allow user to preview the selected videos with the returned crop values (maybe something similar to [CropTransform](https://github.com/LeGoffMael/video_editor/blob/master/lib/src/widgets/transform.dart) widget from video_editor).
- then it would be up to the user to actually perform the video crop encoding (by using FFmpeg, their own video server, ...)

Other features might be requested (trim, maxDuration, minDuration, ...) so this is just a basic implementation of what could be needed.

**Comment by LeGoffMael** [comment]
New prerelease `v3.0.0-dev.1` is out. It now supports video 🎉

The video processing must be handle on your side.

Please check the readme, changelog and migration_guide to see what changed.
You can also check the example app to see how to use it.

I made a prerelease to be sure everything is fine before the major release. Please let me know if there is any issues.

**Comment by joachimbulow** [comment]
Wow nuts!
Unfortunately we had to implement out own solution from scratch.
Well done though, congrats 🎉 🎉

**Comment by joachimbulow** [comment]
CLosing this i suppose ^^
