### ISSUE TITLE
The restorable picker is not responding when opened for the first time, showing an empty list.

### ISSUE THREAD

**Issue by rajivmegamind** [LeGoffMael/insta_assets_picker#43]
@LeGoffMael 👀

**When I open the **Restore Picker** asset for the first time in the phone, it shows me an empty list and after killing the app and opening it again, it works perfectly. This works fine in all types of pickers, only the problem is in restorable pickers.**

Steps : 
1. Install the Fresh app and open the restore picker, this problem will replicate.
2. Close the app and open it again, this problem is gone.

Note : - The issue only occurs on a fresh install when the app is opened for the first time.

**Please Fix this issue ASAP because my whole project depends on this package**

Use Package Version : - insta_assets_picker: ^2.3.0

 See Image👇👇👇👇👇👇👇👇👇👇

![IMG_1366](https://github.com/LeGoffMael/insta_assets_picker/assets/129256821/b72f36f3-48ca-419a-81e5-9d90fb6c9749)

**Comment by LeGoffMael** [comment]
This issue should be available in the new `2.3.1` version !
