### ISSUE TITLE
Android apk build error

### ISSUE THREAD

**Issue by ziponia** [LeGoffMael/insta_assets_picker#51]
Hi! @LeGoffMael 

thank you for providing a great package.

I'm in the middle of a migration to version 3.24.0 of flutter, and I noticed that the migration tests in your project run differently than expected.

I expected a problem in my project, but it was not solved, so I tried to clone your project and it is reproducing the problem.

I would appreciate it if you could tell me how to solve it.

## Error Print ##

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':insta_assets_crop:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR: /my/home/path/insta_assets_picker/example/build/insta_assets_crop/intermediates/merged_res/release/values/values.xml:194: AAPT: error: resource android:attr/lStar not found.
```

## flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.4)
[✓] VS Code (version 1.92.0)
[✓] Connected device (5 available)
[✓] Network resources
```

## Reproduce

1. current project clone
2. `flutter pub get`
3. `cd example`
4. `flutter run --release` or `flutter build apk`

There seems to be no problem in debug mode or 'flutter build appbundle'.

## Additional information

There seems to be no problem in debug mode or 'flutter build appbundle'.

**Comment by ps6067966** [comment]
![image](https://github.com/user-attachments/assets/066c09a4-80e3-46d6-9c2b-dbc71e007205)

Same error in 
insta_assets_picker : 3.0.0-dev.1
insta_assets_crop: 0.1.0-dev.2


Please fix this. I need to deliver to client this week. Please please. 
@LeGoffMael

**Comment by ziponia** [comment]
@ps6067966 

No.

As long as it's not an apk, it builds normally, so it wasn't a very urgent issue for me.

If you need to distribute it to your customers right away
Use firebase distribution tools or internal tracks

I don't think the maintainer is interested in this library ;(

**Comment by LeGoffMael** [comment]
HI there, 

It seems to be an issue with the Flutter 3.24.0.

It has been reported [here](https://github.com/livekit/client-sdk-flutter/issues/569) and [here](https://github.com/MaikuB/flutter_local_notifications/issues/2385).

As [mentioned in the above link](https://github.com/livekit/client-sdk-flutter/issues/569#issuecomment-2275686786) adding this workaround in `android/build.gradle` seems to solve the issue
```
subprojects {
    afterEvaluate { project ->
        if (project.plugins.hasPlugin("com.android.application") ||
                project.plugins.hasPlugin("com.android.library")) {
            project.android {
                compileSdkVersion 34
                buildToolsVersion "34.0.0"
            }
        }
    }
    // l original code here i.e: project.evaluationDependsOn(':app')
}
```

**Comment by LeGoffMael** [comment]
This error should be gone in the latest 3.1.0 version
