### ISSUE TITLE
isOriginal must be provided

### ISSUE THREAD

**Issue by baaakgun** [LeGoffMael/insta_assets_picker#54]
Sincerely appreciate your package!!!!

My flutter version is. 3.26.0-0.1.pre
flutter doctor is clean
I'm currently using 3.0.0-dev.1, facing an issue.

Error (Xcode): ../../../.pub-cache/hosted/pub.dev/insta_assets_picker-3.0.0-dev.1/lib/src/widget/video_player_mixin.dart:155:30: Error: Required named parameter 'isOriginal' must be provided.

Cannot build android and ios. 

I found an issue regarding 'isOriginal' in wechat_assets_Picker.
In its changelog of 9.2.2, Uses correct isOriginal for the LocallyAvailableBuilder.

How can I fix it??

**Comment by LeGoffMael** [comment]
This error should be gone in the latest 3.1.0 version
